services:
  
  server:
    build:
        context: .
        dockerfile: docker/Dockerfile
    ports:
        - '8000:8000'
    restart: always

  db:
    image: postgres:17-alpine
    ports:      
      - 5432:5432
    # volumes:
    #   - ~/podcast/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - PGUSER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db